package com.example.gerenciamentoviagens.data.remote

import com.google.gson.annotations.SerializedName

// Models for Gemini Request
data class GeminiRequest(
    val contents: List<Content>
)

data class Content(
    val parts: List<Part>
)

data class Part(
    val text: String
)

// Models for Gemini Response
data class GeminiResponse(
    val candidates: List<Candidate>?
)

data class Candidate(
    val content: Content?
)

// Models for the Itinerary JSON generated by Gemini
data class ItineraryResponse(
    val destino: String,
    val dias: List<DayPlan>
)

data class DayPlan(
    val dia: Int,
    val atividades: List<ActivityPlan>
)

data class ActivityPlan(
    val horario: String,
    val descricao: String,
    @SerializedName("custo_estimado")
    val custoEstimado: String
)
